fix: modify the path to kglobalshortcutsrc package.
radxa-pkg/radxa-system-config pull request #7
Opened 2024-04-10 11:12 UTC by CodeChenL

Fix can't control user default kglobalshortcutsrc

2024-04-10 11:28 UTC, CodeChenL commented
@RadxaYuntian request a review

2024-04-11 02:22 UTC, RadxaYuntian requested changes
另外commit标题结尾不要带句号

2024-04-11 02:22 UTC, RadxaYuntian commented on debian/radxa-system-config-bookworm.lintian-overrides
> +radxa-system-config-bookworm: package-contains-file-in-etc-skel
缺少结尾空行

2024-04-11 03:11 UTC, RadxaYuntian approved these changes

2024-04-11 03:11 UTC, merged