fix: remove dpkg-divert from other packages before install
radxa-pkg/radxa-system-config pull request #8
Opened 2024-04-17 08:11 UTC by CodeChenL

2024-04-17 10:12 UTC, RadxaYuntian requested changes
应该用debian replaces & brakes来先移除老版本吧：https://www.debian.org/doc/debian-policy/ch-relationships.html#overwriting-files-in-other-packages

2024-04-17 10:48 UTC, RadxaYuntian requested changes

2024-04-17 10:48 UTC, RadxaYuntian commented on debian/radxa-system-config-bookworm.preinst
> +#!/bin/bash
bashism

2024-04-17 10:51 UTC, RadxaYuntian commented on debian/control
> +        radxa-system-config-rockchip (<< 0.5.3),
rockchip 0.5.2好像没有你那个文件吧？https://github.com/radxa-pkg/radxa-system-config/commits/main/?after=b4422011fab110780da624d711aa416cc398e2aa+34

2024-04-17 11:03 UTC, CodeChenL commented
看错包名了https://github.com/radxa-pkg/radxa-system-config/commit/3ad75dbde8357d4d23ffeab45a3708cde6fe7e88#diff-3768c8cf3c7a5c19014f54dcb6860e18a247bcc7890a65cefb3c537391316537，应该是和bullseye互斥就行了

2024-04-17 11:19 UTC, RadxaYuntian requested changes

2024-04-17 11:19 UTC, RadxaYuntian commented on debian/control
这几个suite包都提供了radxa-system-config虚拟包，按照debian policy把缺少的Conflicts和Replaces补上应该可以吧？
https://www.debian.org/doc/debian-policy/ch-relationships.html#replacing-whole-packages-forcing-their-removal

2024-04-18 07:35 UTC, RadxaYuntian requested changes
如果可以的话要把其他几个distro的包也加上这两个属性

2024-04-18 08:41 UTC, RadxaYuntian requested changes
radxa-system-config-buster也加上吧

2024-04-18 09:44 UTC, RadxaYuntian requested changes
rebase

2024-04-18 10:08 UTC, RadxaYuntian approved these changes

2024-04-18 10:08 UTC, merged